# Generated by Django 6.0.7 on 2026-08-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('caption_font', models.CharField(choices=[('inter', 'Inter (modern)'), ('serif', 'Georgia (warm serif)'), ('mono', 'JetBrains Mono (typewriter)')], default='inter', max_length=50)),
                ('caption_color', models.CharField(default='#FFFFFF', max_length=9)),
                ('caption_position', models.CharField(choices=[('lower_third', 'Lower third'), ('center', 'Center'), ('top', 'Top')], default='lower_third', max_length=20)),
                ('brand_logo', models.CharField(blank=True, max_length=500)),
                ('brand_lower_third', models.CharField(blank=True, max_length=200)),
                ('default_template', models.CharField(default='stage_solo_speaker', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='webui.clientproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('caption_override', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='webui.episode')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='webui.episode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
