# Generated by Django 6.0.7 on 2026-09-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='zoom_punch',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='caption_font',
            field=models.CharField(choices=[('impact', 'Impact (bold viral / Hormozi)'), ('heavy', 'Arial Black (clean heavy)'), ('inter', 'Inter (modern sans)'), ('serif', 'Georgia (warm serif)'), ('mono', 'JetBrains Mono (typewriter)')], default='impact', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='default_template',
            field=models.CharField(default='full_bleed_solo', max_length=50),
        ),
    ]
