# Generated by Django 6.0.7 on 2026-09-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_clientproject_zoom_punch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='master_audio',
            field=models.BooleanField(default=True),
        ),
    ]
