# Generated by Django 6.0.7 on 2026-09-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_clientproject_master_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='hook_card',
            field=models.BooleanField(default=True),
        ),
    ]
