# Generated by Django 6.0.7 on 2026-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_clientproject_hook_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='caption_template',
            field=models.CharField(choices=[('hormozi_pop', 'Hormozi Viral Pop (Impact, 1.22x Word Pop, Emojis)'), ('beast_neon', 'MrBeast Dynamic (Heavy Sans, Neon Cyan, Bold Stroke)'), ('minimal_clean', 'Clean Minimalist / Ali Abdaal (Inter Sans, Soft Coral)'), ('documentary', 'Vox / Documentary (Georgia Serif, Editorial Red)'), ('cyber_terminal', 'Cyber Tech (JetBrains Mono, Terminal Green)')], default='hormozi_pop', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='caption_color',
            field=models.CharField(default='#FFEA00', help_text='Active word highlight color', max_length=9),
        ),
    ]
