# Generated by Django 6.0.7 on 2026-09-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0005_clientproject_caption_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='podcast_solo_switch',
            field=models.BooleanField(default=True),
        ),
    ]
