# Generated by Django 6.0.7 on 2026-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0006_clientproject_podcast_solo_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='video_filter',
            field=models.CharField(choices=[('vivid_pop', 'Vivid Pop (Speaker Focus: Contrast, Vibrance, Sharpness)'), ('warm_studio', 'Warm Studio (Golden Tone, Soft Glow)'), ('clean_crisp', 'Clean Crisp (High Clarity, Natural Tone)'), ('cinematic', 'Cinematic Punch (Filmic Shadows, Moody Vignette)'), ('none', 'None (Original Raw Video)')], default='vivid_pop', max_length=50),
        ),
    ]
