# Generated by Django 6.0.7 on 2026-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0007_clientproject_video_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renderjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20),
        ),
    ]
